### ISSUE TITLE
ERROR: The decoder library file does not exist

### ISSUE THREAD

**Issue by kmrambo** [mozilla/DeepSpeech#1204]
I am trying to train the model based on Common Voice training data. I have installed all the requirements as per requirements.txt. I have downloaded the CV data and imported it using the script(import_cv.py). As per the readme file, I have also downloaded the native client using the following command (`python util/taskcluster.py --target .`). I can now see a separate folder created for the native-client files.
 Now, if I run the training command as per the readme file, I get an error stating that the "Decoder library file does not exist". I don't understand why this is happening even though I downloaded the native client files as per the readme. Below is the command that I have run:

`python DeepSpeech.py --train_files /Users/kmrambo/DeepSpeech-master/CV/cv-valid-train.csv --dev_files /Users/kmrambo/DeepSpeech-master/CV/cv-valid-dev.csv --test_files /Users/kmrambo/DeepSpeech-master/CV/cv-valid-test.csv`

When I run the above command I get the below error:

**> ERROR: The decoder library file does not exist. Make sure you have downloaded or built the native client binaries and pass the appropriate path to the binaries in the --decoder_library_path parameter.
Traceback (most recent call last):
  File "DeepSpeech.py", line 1861, in <module>
    tf.app.run()
  File "/Users/kmrambo/anaconda2/envs/deepspeech/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1813, in main
    initialize_globals()
  File "DeepSpeech.py", line 334, in initialize_globals
    custom_op_module = tf.load_op_library(FLAGS.decoder_library_path)
  File "/Users/kmrambo/anaconda2/envs/deepspeech/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/Users/kmrambo/anaconda2/envs/deepspeech/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(native_client/libctc_decoder_with_kenlm.so, 6): image not found**

Now I try adding the decoder_library_path parameter to the command as below:

`python DeepSpeech.py --train_files /Users/kmrambo/DeepSpeech-master/CV/cv-valid-train.csv --dev_files /Users/kmrambo/DeepSpeech-master/CV/cv-valid-dev.csv --test_files /Users/kmrambo/DeepSpeech-master/CV/cv-valid-test.csv --decoder_library_path /Users/kmrambo/DeepSpeech-master/libctc_decoder_with_kenlm.so`

Again I get a different error as shown below:

**Traceback (most recent call last):
  File "DeepSpeech.py", line 1861, in <module>
    tf.app.run()
  File "/Users/kmrambo/anaconda2/envs/deepspeech/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1813, in main
    initialize_globals()
  File "DeepSpeech.py", line 334, in initialize_globals
    custom_op_module = tf.load_op_library(FLAGS.decoder_library_path)
  File "/Users/kmrambo/anaconda2/envs/deepspeech/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/Users/kmrambo/anaconda2/envs/deepspeech/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/Users/kmrambo/DeepSpeech-master/libctc_decoder_with_kenlm.so, 6): no suitable image found.  Did find:
	/Users/kmrambo/DeepSpeech-master/libctc_decoder_with_kenlm.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/kmrambo/DeepSpeech-master/libctc_decoder_with_kenlm.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00**

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS High Sierra
- **TensorFlow version (use command below)**: 1.4.0
- **Python version**: 2.7.14
- **GPU model and memory**: Only CPU

**Comment by lissyx** [comment]
@kmrambo Which file did you downloaded ?

**Comment by kmrambo** [comment]
Sorry I have downloaded the wrong native-client file. I downloaded the mac compatible verison and it is working now

**Comment by kmrambo** [comment]
I trained the model for 10 epochs and got the following logs:
**I STARTING Optimization
I Training of Epoch 0 - loss: inf
I Training of Epoch 1 - loss: 423.264867
I Training of Epoch 2 - loss: 371.507345
I Training of Epoch 3 - loss: 353.714516
I Training of Epoch 4 - loss: 365.876526
I Training of Epoch 5 - loss: 363.773275
I Training of Epoch 6 - loss: 337.367915
I Training of Epoch 7 - loss: 317.273590
I Training of Epoch 8 - loss: 310.249738
I Training of Epoch 9 - loss: 310.849909
I FINISHED Optimization - training time: 0:47:59
Loading the LM will be faster if you build a binary file.
Reading data/lm/lm.binary
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
libc++abi.dylib: terminating with uncaught exception of type lm::FormatLoadException: native_client/kenlm/lm/read_arpa.cc:65 in void lm::ReadARPACounts(util::FilePiece &, std::vector<uint64_t> &) threw FormatLoadException.
first non-empty line was "version https://git-lfs.github.com/spec/v1" not \data\. Byte: 43
Abort trap: 6**

Did the training complete successfully? If it has completed successfully, how do i predict new data using this model. I find some checkpoints have been created in the checkpoint directory

**Comment by reuben** [comment]
You did not install Git LFS as documented here: https://github.com/mozilla/DeepSpeech#getting-the-code

You'll have to install it and do a `git lfs checkout` to pick up the large binary files needed for training.

**Comment by kmrambo** [comment]
@reuben Could you please be more specific? Did you answer for the Native client error I posted or the results of the training logs that I posted?

**Comment by reuben** [comment]
I thought the native client error was fixed? You said so in a comment above. I was talking about the training error.

**Comment by kmrambo** [comment]
Yep the native client error is fixed. Thanks. I will try as you said and reply back

**Comment by kmrambo** [comment]
@reuben I still cannot understand why git lfs is required. I have downloaded all the files locally to my computer. I have not cloned the repository. Could you please clarify?

**Comment by reuben** [comment]
Can you please clarify how you're training without cloning the repository? Did you manually download each file in the repository?

**Comment by kmrambo** [comment]
@reuben I have downloaded the whole repository as a zip file . You have two options (Either clone or download as a zip file). And then I have extracted all the files out of it.

**Comment by reuben** [comment]
I just checked and the zip/tarballs don't contain the full Git LFS files, so you'll need to install Git/Git LFS and clone the repository for training. This is a pretty bad behavior on GitHub's part since a tarball without these files is useless, you can't even do a `git lfs checkout` afterwards.

**Comment by kdavis-mozilla** [comment]
We should file a bug against GitHub, but where?
